### ISSUE TITLE
error in tashkeel

### ISSUE THREAD

**Issue by a7madM** [Barqawiz/Shakkala#1]
text: الحمد لله رب العالمين 
processed text: الْحَمْدُ لِلَّهِ رَبُّ الْعَالِمِين
it should be: الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
explanation: 
لله: لفظ الجلالة و اسم مجرور بحرف اللام و علامة الجر الكسرة
رب: نعت مجرور بالتبعية لـ الله و علامة الجر الكسرة

best wishes

**Comment by Barqawiz** [comment]
Thanks for testing Shakkala, we will include the fix text in next version training data for the model to learn from it.

**Comment by Barqawiz** [comment]
تم اضافة الجملة الى ملفات التدريب في النسخة الثانية
