### ISSUE TITLE
Not an issue really, just make a LICENSE.md file

### ISSUE THREAD

**Issue by iskandergaba** [Barqawiz/Shakkala#2]
It is more common to have a "LICENSE.md" file rather than including the license inside "README.md". It makes it apparent in project repository info and it can be easily generated. See this [link](https://help.github.com/articles/adding-a-license-to-a-repository)

Other than that, I like the idea of this project, and I will definitely spend some time with code.
وَفَقَكَ اللَّه

**Comment by Barqawiz** [comment]
Noted will update license based on this

**Comment by Barqawiz** [comment]
Done تم الاضافة
