### ISSUE TITLE
Model design image unclear

### ISSUE THREAD

**Issue by treya-lin** [Barqawiz/Shakkala#27]
Hello, the image of model design is not quite clear. Is it possible to replace them with a clearer version? Many thanks.

**Comment by tuqfyC-8xobzu-kemwyg** [comment]
> ello, the image of model design is not quite clear. Is it possible

**Comment by Barqawiz** [comment]
Unfortunately, I cannot export a new one as the data is old, but I can explain the layers.

- bi-directional RRN.
- batch normalisation.
- bi-directional RRN.
- fully dense connected layer.

Two metrics used for testing data:
- Loss.
- Accuracy.
