### ISSUE TITLE
لغة أكلوني البراغيث!

### ISSUE THREAD

**Issue by jotIO** [Barqawiz/Shakkala#3]
This might be a premature issue, But i have tried with different forms; and It seems that Shakkala doesn't resolve it at all. 
Text: أكلوني البراغيث
Expected output: أَكَلُونِي الْبَرَاغِيثُ
Actual output: أَكَلُونِي الْبَرَاغِيثَ

Text: يتعاقبون فيكم ملائكة بالليل وملائكة بالنهار
Expected output: يَتَعَاقَبُونَ فِيكُمْ مَلَائِكَةٌ بِاللَّيْلِ وَمَلَائِكَةٌ بِالنَّهَارِ 
Actual output: يْتَعَاقِبُونَ فِيكُمْ مَلَائِكَةً بِاللَّيْلِ وَمَلَائِكَةِ بِالنَّهَار

Text: ضربوني الأولاد
Expected output: ضَرْبُونِي الْأَوْلَادُ
Actual output: ضَرْبُونَى الْأَوْلَادَ

<p dir='rtl'>- ما نوعية المساهامات الممكن تقديمها غير التبليغ عن الأخطاء؟</p>
<p dir='rtl'>- -  شكرًا على المجهود الأكثر من عظيم في هذا المشروع.</p>

**Comment by Barqawiz** [comment]
شكرا جزيلا على التبليغ 
مساعدة في التبليغ عن الاخطاء المتكررة بنفس الطريقة و التي تمثل pattern
 مفيد جدا و خاصة توفير عدة امثلة كما فعلت وهذا كفاية مبديا اما اردت المزيد يمكنك
 المساعدات في عمل plugins 
على المتصفح مثلا او الاليميل او الورد بريس سيكون مفيد جدا
للتوضيح تم برمجة شكالة باستخدام 
tensorflow و keras

و لعمل بلاج ان عليك استخراج الاوزان من كيرا و استعمالها في اللغات الاخرى عن طريق المكتبات المتوفرة و اذا احتجت اي صيغة مختلفة للاوزات يمكنني توفيرها لك

**Comment by youssifsayed** [comment]
<p dir='rtl'>جميل. في أقرب فرصة سأعمل على ربط لشكالة لجافاسكريبت، وتوفيره على NPM يمكن مطوري الويب استخدام شكالة بسهولة، سأحول بدء العمل في عطلة الأسبوع القادم -إن شاء الله.</p>
<p dir='rtl'>شكرًا.</p>

**Comment by Barqawiz** [comment]
شكرا و اي سؤال او استفسار او مساعدة تواصل معي على 
BarqawiCloud@gmail.com

**Comment by Barqawiz** [comment]
تم اضافة الجمل الى كلمات التدريب للنسخة ٢ 
بعد اطلاق النسخة و التي تحتاج ما يقارب الشهر يرجى المراجعة
