### ISSUE TITLE
 TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by hacyber18** [Barqawiz/Shakkala#38]
Hey there. I love your work on the diacritization, I am actually implementing the Shakkala function when creating an object and I get this error below. Any idea what's wrong, I have changed the folder path and checked the class to see whether there is any spelling error but to no avail.

TypeError                                 
Traceback (most recent call last)
[<ipython-input-34-d7904337a874>](https://localhost:8080/#) in <module>
----> 1 Shakkala('/content/Shakkala',version=3)

TypeError: 'module' object is not callable
PS: I am implementing the program in google colab

**Comment by Barqawiz** [comment]
Do you phase the same error in local setup or only using google colab ?

show me the full log of the error please.

Note that I updated the Tensorflow version in case that's help.

**Comment by Barqawiz** [comment]
You can use Shakkala with pip command now:
pip install shakkala

This will make colab integration easier.

**Comment by hacyber18** [comment]
Dear Ahmed
I am really sorry for not replying, it was unprofessional from my part
because of tight load of work on my end. But I am very thankful for your
reply and I would check out the solution you provided.
Then again, sorry for the inconvenience and appreciate your support

Regards
Hammad manzoor

**Comment by Barqawiz** [comment]
Hello,

No worries at all, actually you replied in reasonable time.

If the solution did not work , you can contact me to try to fix it.
________________________________
