### ISSUE TITLE
مشكلة في التشكيل

### ISSUE THREAD

**Issue by NacTarek** [Barqawiz/Shakkala#4]
النص: الجزائر جميلة 
التشكيل من الشبكة: الْجَزَائِرِ جَمِيلَةٌ
والأصح: الْجَزَائِرٌ جَمِيلَةٌ
لأنه مبتدأ مرفوع.

**Comment by Barqawiz** [comment]
ساقوم باضافة التصليح الى تدريب النسخة الجديدة و لكن انت تقصد الجزائرُ جَمِيلَةٌ ؟

**Comment by NacTarek** [comment]
نعم أخطأت في الشكل لأن الضمة واللضمتين متشابهتين في المارك داون الخاص بهذا الموقع.. 
ننتظر هذه الإضافة..
بالتوفيق..

**Comment by Barqawiz** [comment]
هل يمكنك المساعدة في توفير عدة جمل مثلا ٨ جمل تحتوي كلمة الجزائرُ لنتاكد ان الشبكة ستتعلمها بالشكل الصحيح

**Comment by NacTarek** [comment]
الجزائرُ جميلة 
الجزائرُ لها خيرات متنوعة
الجزائرُ دولةٌ إفريقيةٌ
الجزائرُ دولةٌ عربيةٌ
الجزائرُ دولةٌ مغاربيةٌ 
الجزائرُ جارتها المغرب
الجزائرُ تشرف على البحر الأبيض
الجزائرُ دولة بيترولية

**Comment by Barqawiz** [comment]
شكرا جزيلا

**Comment by Barqawiz** [comment]
تم اضافة الجمل الى النسخة الثانية و عند اطلاقها سيتم التصحيح
