### ISSUE TITLE
Adding a pypi package

### ISSUE THREAD

**Issue by yoosif0** [Barqawiz/Shakkala#6]
Thank you for the great project.

Are you interested in adding a pypi package? 
This way, we could use it via pip
`pip install shakkala`

**Comment by Barqawiz** [comment]
Great suggestion, if you can create pull request with this update will accept it

**Comment by x5engine** [comment]
هوا في ايه

**Comment by MoeBensu** [comment]
@Barqawiz I guess, this is really a nice to have for easier usage. You can assign me to it, if you still want it.

**Comment by Barqawiz** [comment]
@MoeNeuron I started to prepare the pip publish in the following branch:
https://github.com/Barqawiz/Shakkala/tree/prepare-pip-install

but something does not connect after the publish, lets meet based on your availability to validate.

**Comment by Barqawiz** [comment]
The issue is resolved and shakkala is publish.

pip install shakkala==1.6

For more details: https://pypi.org/project/shakkala/1.6/

Thanks for the suggestion.
